### ISSUE TITLE
Add support for VSCode Web

### ISSUE THREAD

**Issue by lazuee** [andrii-bohdan/vscode-git-commit-wizard#10]

**Comment by andrii-bohdan** [comment]
> 

**VSCode Web limitation**
 Since VS Code for the Web runs completely within the browser, some experiences will naturally be more constrained when compared to what you can do in the desktop app.
I will try to fix that in the next update

**Comment by lazuee** [comment]
@andrii-bohdan Okay, I really like this extension... 
Sometimes I used github.dev to edit my repo because the vscode/vscodium app sometimes getting laggy,..

**Comment by andrii-bohdan** [comment]
> @andrii-bohdan Okay, I really like this extension... Sometimes I used github.dev to edit my repo because the vscode/vscodium app sometimes getting laggy,..

Hi, finally the extension is also available on the Web version. Today I made few test unfortunately the way how I handle git repository in the app version is not working properly in web version. I'll take some more time to find workaround. 

![preview-wizard](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/61162113/d5fb6324-cf66-4149-bb57-44601d3786df)
