### ISSUE TITLE
[feature request] Add an icon on SCM title bar

### ISSUE THREAD

**Issue by Alecton4** [andrii-bohdan/vscode-git-commit-wizard#29]
It would be nice if an icon could be added to the SCM title bar for quick access like [another extension](https://github.com/RedJue/git-commit-plugin#quick-start) (see the gif in *Quick Start > 2*).

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/f5142d2c-e7d5-41ee-ad7e-d6d9a519efed)

**Comment by andrii-bohdan** [comment]
> It would be nice if an icon could be added to the SCM title bar for quick access like [another extension](https://github.com/RedJue/git-commit-plugin#quick-start) (see the gif in _Quick Start > 2_).
> 
> ![image](https://user-images.githubusercontent.com/43232804/267572592-f5142d2c-e7d5-41ee-ad7e-d6d9a519efed.png)

Hi, thank you for advice this feature will be included into the next release

**Comment by Alecton4** [comment]
Thanks for your great work @andrii-bohdan ! With this added, maybe we could also include a setting to hide the icon on the status bar optionally.

**Comment by andrii-bohdan** [comment]
![icons-visibility](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/61162113/7ecc9329-d221-4985-accf-613fb647f9ad)


> Thanks for your great work @andrii-bohdan ! With this added, maybe we could also include a setting to hide the icon on the status bar optionally.

This feature will be available in the next update. Remeber update and reload extension

**Comment by Alecton4** [comment]
Thank you @andrii-bohdan! While hiding icons on SCM title bar is a great feature, my intention is to hide the icon on the status bar:

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/c4befa1e-3e3b-44e2-be7a-ade483d7414a)

**Comment by andrii-bohdan** [comment]
> Thank you @andrii-bohdan! While hiding icons on SCM title bar is a great feature, my intention is to hide the icon on the status bar:
> 
> ![image](https://user-images.githubusercontent.com/43232804/270004358-c4befa1e-3e3b-44e2-be7a-ade483d7414a.png)

Now you can toggle the visibility of status bar 🤗 
![status-bar-visibility](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/61162113/b48f82c3-9649-4627-99ee-8f5e412ffb93)
