### ISSUE TITLE
[feature request] Auto select repo

### ISSUE THREAD

**Issue by Alecton4** [andrii-bohdan/vscode-git-commit-wizard#41]
Currently, when clicking the icon on a specific repo (in a workspace with multiple repos), the repo selector is invoked. It might be better if the corresponding repo can be automatically selected when clicking the icon for a repo.

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/d271ba52-7021-4b9d-bc61-999298dcc408)

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/03af2224-51f2-4d89-8c9a-fd526f0c2578)

**Comment by Alecton4** [comment]
@andrii-bohdan I found another extension having the desired behavior. It would be great if this helps: https://github.com/seatonjiang/gitmoji-vscode/blob/main/src/extension.ts#L45

**Comment by andrii-bohdan** [comment]
Hi, thank you for good idea. The feature is already online you can test it https://github.com/andrii-bohdan/vscode-git-commit-wizard/releases/tag/v2.0.22. I also included possibility use repository list in case when somebody open extension using keybinding

![new-feature](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/61162113/3a08d5ce-3542-41f0-be8b-d1253426d5dd)
