### ISSUE TITLE
Icon on SCM title

### ISSUE THREAD

**Issue by Alecton4** [andrii-bohdan/vscode-git-commit-wizard#45]
Icon on SCM title looks strange after updating to VSCode 1.83.0. Maybe they changed icon identifier or something?

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/911338ca-1159-4149-abfc-bde64a8ab71c)

**Comment by andrii-bohdan** [comment]
> Icon on SCM title looks strange after updating to VSCode 1.83.0. Maybe they changed icon identifier or something?
> 
> 
> 
> ![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/911338ca-1159-4149-abfc-bde64a8ab71c)
> 
> 

Interesting. I will test it later

**Comment by andrii-bohdan** [comment]
> > Icon on SCM title looks strange after updating to VSCode 1.83.0. Maybe they changed icon identifier or something?
> > ![image](https://user-images.githubusercontent.com/43232804/272792328-911338ca-1159-4149-abfc-bde64a8ab71c.png)
> 
> Interesting. I will test it later

Fixed (https://github.com/andrii-bohdan/vscode-git-commit-wizard/releases/tag/v2.0.23). There was new api rules related to  scm/title icon. Enjoy 😃
