### ISSUE TITLE
SCM Icon exists even when no git repo is detected

### ISSUE THREAD

**Issue by Alecton4** [andrii-bohdan/vscode-git-commit-wizard#51]
Maybe our extension's icon on the SCM title should not appear if there is no git repo detected?

![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/bd8f06e2-6ab3-471c-ac47-3841dad4df2c)

**Comment by andrii-bohdan** [comment]
> Maybe our extension's icon on the SCM title should not appear if there is no git repo detected?
> 
> 
> 
> ![image](https://github.com/andrii-bohdan/vscode-git-commit-wizard/assets/43232804/bd8f06e2-6ab3-471c-ac47-3841dad4df2c)
> 
> 

Thank you.I will fix it in the next update🤗

**Comment by andrii-bohdan** [comment]
I apologize for this long wait.
Fixed https://github.com/andrii-bohdan/vscode-git-commit-wizard/pull/52
