### ISSUE TITLE
Remove "Formatters" category from manifest

### ISSUE THREAD

**Issue by sergei-dyshel** [andrii-bohdan/vscode-git-commit-wizard#59]
This extension pops up in search when searching for extension that provides formatting commit messages. But after installing one suddenly realizes that formatting is not supported. Please correct declared categories.

**Comment by andrii-bohdan** [comment]
> This extension pops up in search when searching for extension that provides formatting commit messages. But after installing one suddenly realizes that formatting is not supported. Please correct declared categories.

Could you provide more detail about your problem ?

**Comment by sergei-dyshel** [comment]
Quoting `package.json`:
```
  "categories": [
    "Other",
    "Formatters",
    "SCM Providers"
  ],
```

This extension does NOT provide formatter, so it shouldn't be categorized a such. It's not really a problem, just a description correctness issue.
